# Imports for this project
from requests import get
from pprint import PrettyPrinter

# Below is the base api endpoint and my unique API key.
BASE_URL = "https://free.currconv.com/"
API_KEY = "ed11d4dc9a777826aae3"

printer = PrettyPrinter()

# This function gets a list of all currencies and sorts them alphabeticaly 
def get_currencies():
    endpoint = f"api/v7/currencies?apiKey={API_KEY}"
    url = BASE_URL + endpoint
    data = get(url).json()['results']

    data = list(data.items())

    data.sort()

    return data

# This function takes the list generated by the get_currencies function and displays it 
def print_currencies(currencies):
    for name, currency in currencies:
        name = currency['currencyName']
        _id = currency['id']

        symbol = currency.get('currencySymbol', '')
        print(f"{_id} - {name} - {symbol}")

# This function gets the exchnage rate between two inputed currencies 
def exchnage_rate(currency1, currency2):
    endpoint = f"api/v7/convert?q={currency1}_{currency2}&compact=ultra&apiKey={API_KEY}"
    url = BASE_URL + endpoint
    data = get(url).json()

    if len(data) == 0:
        print('Invalid currencies')
        return

    rate = list(data.values())[0]
    print(f"Conversion rate from {currency1} -> {currency2} = {rate}")

    return rate

# This function converts a given amount of one currency to another currency
def convert(currency1, currency2, amount):
    rate = exchnage_rate(currency1, currency2)
    if rate is None:
        print('One or more of the currency symbols were invalid')
        return

    try: 
        amount = float(amount)
    except: 
        print('Invalid amount!')
        return

    converted_amount = rate * amount 
    print(f"{amount} {currency1} is equal to {converted_amount} {currency2}")
    return converted_amount

# This is the main function.
# It contains a while loop that allows a user to use the above funtions through three commands 
def main():
    currencies = get_currencies()

    print("Welcome to the currency converter!")
    print("Choose a command or enter q to quit at anytime.")
    print("List - list all currencies")
    print("Convert - convert an amount from one currency to another")
    print("Rate - get the exchnage rate of two different currencies")
    print()

    while True: 
        command = input("Enter a command: ").lower()

        if command == "q":
            break
        elif command == "list":
            print_currencies(currencies)
        elif command == "convert":
            currency1 = input("Enter a base currency three letter id: ").upper()
            amount = input(f"Enter the amount you wish to convert in {currency1}: ")
            currency2 = input("Enter the three letter id of the currency you wish to convert to: ").upper()
            convert(currency1, currency2, amount)
        elif command == "rate":
            currency1 = input("Enter a base currency three letter id: ").upper()
            currency2 = input("Enter the three letter id of the currency you wish to convert to: ").upper()
            exchnage_rate(currency1, currency2)
        else:
            print("Unknown command! Please try again.")

main()

